name: clockin-bot
services:
  db:
    image: mongo:latest
    container_name: clock-mongodb
    ports:
      - 27016:27017
    volumes:
      - db-data:/data/db
  web:
    depends_on:
      - db
    build: ./client
    container_name: clock-web
    environment:
      NODE_ENV: production
    env_file:
      - ./client/.env.local
      - ./client/.env.production
    ports:
      - 3000:3000
  server:
    build: ./server
    container_name: clock-discord
    env_file:
      - ./server/.env
    ports:
      - 8000:8000
volumes:
  db-data:
