name: clockin-bot
services:
  db:
    image: mongo:4.4.6
    container_name: clock-mongodb
    ports:
      - 27016:27017
    volumes:
      - db-data:/data/db
  web:
    depends_on:
      - db
    build: ./client
    container_name: clock-web
    env_file:
      - ./client/.env
      - ./client/.env.local
      - ./client/.env.production.local
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  server:
    build: ./server
    container_name: clock-discord
    env_file:
      - ./server/.env
      - ./server/.env.local
    ports:
      - 7546:7546
    # volumes:
    #   - ./server/modules/data.json:/app/modules/data.json
volumes:
  db-data:
