name: clockin-bot
services:
  db:
    image: mongo:4.4.6
    container_name: clock-mongodb
    networks:
      - clock-network
    ports:
      - 27016:27017
    volumes:
      - db-data:/data/db
  web:
    depends_on:
      - db
    build:
      context: ./client
    container_name: clock-web
    env_file:
      - ./client/.env
      - ./client/.env.local
      - ./client/.env.production.local
    networks:
      - clock-network
    ports:
      - 3000:3000
  server:
    build: ./server
    container_name: clock-discord
    env_file:
      - ./server/.env
      - ./server/.env.local
    networks:
      - clock-network
    volumes:
      - discord-data:/app/modules/data.json
    ports:
      - 7546:7546
volumes:
  db-data:
  discord-data:
networks:
  clock-network:
    driver: bridge