name: clockin-bot
services:
  webdb:
    image: mongo:4.4.6
    container_name: clock-mongodb
    networks:
      - clock-network
    ports:
      - 27016:27017
    volumes:
      - db-data:/data/db
  web:
    depends_on:
      - webdb
    build:
      context: ./client
    container_name: clock-web
    env_file:
      - ./client/.env
      - ./client/.env.local
      - ./client/.env.production.local
    networks:
      - clock-network
      - caddy_network
    ports:
      - 3000:3000
  server:
    depends_on:
      - serverdb
    build: ./server
    container_name: clock-discord
    env_file:
      - ./server/.env
      - ./server/.env.local
    networks:
      - clock-network
    ports:
      - 7546:7546
  serverdb:
    container_name: clock-postgres
    image: postgres:17-alpine
    volumes:
      - server-discord-data:/var/lib/postgresql/data
    env_file:
      - ./server/.env.local
    environment:
      - DISCORD_PG_HOST=serverdb
      - DISCORD_PG_PORT=5432
      - DISCORD_PG_DB=clockinbot
      - DATABASE_URL=postgresql://${DISCORD_PG_USER}:${DISCORD_PG_PASSWORD}@${DISCORD_PG_HOST}:${DISCORD_PG_PORT}/${DISCORD_PG_DB}
    ports:
      - 5430:5432
    networks:
      - clock-network
volumes:
  db-data:
  server-discord-data:
networks:
  clock-network:
    driver: bridge
  caddy_network:
    external: true