name: clockin-bot
services:
  webdb:
    image: mongo:4.4.6
    container_name: clock-mongodb
    networks:
      - clock-network
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    restart: always
  web:
    depends_on:
      - webdb
    build:
      context: ./client
    container_name: clock-web
    env_file:
      - ./server/.env
      - ./client/.env.docker
    networks:
      - clock-network
      - caddy_network
    ports:
      - 3000:3000
    restart: always
  server:
    depends_on:
      - serverdb
    build: ./server
    container_name: clock-discord
    env_file:
      - ./server/.env
      - ./server/.env.docker
    environment:
      - IS_DOCKER=true
    networks:
      - clock-network
    ports:
      - 7546:7546
    restart: always
  serverdb:
    container_name: clock-postgres
    image: postgres:17-alpine
    volumes:
      - server-discord-data:/var/lib/postgresql/data
    env_file:
      - ./server/.env
      - ./server/.env.docker
    ports:
      - 5432:5432
    networks:
      - clock-network
    restart: always
volumes:
  db-data:
  server-discord-data:
networks:
  clock-network:
    driver: bridge
  caddy_network:
    external: true