name: clockin-bot
services:
  db:
    image: mongo:4.4.6
    container_name: clock-mongodb
    ports:
      - 27016:27017
    volumes:
      - db-data:/data/db
  web:
    depends_on:
      - db
    build: ./client
    container_name: clock-web
    env_file:
      - ./client/.env
      - ./client/.env.local
      - ./client/.env.production.local
    environment:
      NODE_ENV: production
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      MONGODB_URI: ${MONGODB_URI}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      NEXT_PUBLIC_DISCORD_BOT_URL: ${NEXT_PUBLIC_DISCORD_BOT_URL}
    ports:
      - 3000:3000
  server:
    build: ./server
    container_name: clock-discord
    env_file:
      - ./server/.env
      - ./server/.env.local
    environment:
      FLASK_HOST: ${FLASK_HOST}
      FLASK_PORT: ${FLASK_PORT}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      ADDITIONAL_ALLOWED_ORIGINS: ${ADDITIONAL_ALLOWED_ORIGINS}
      BOT_TOKEN: ${BOT_TOKEN}
    ports:
      - 7546:7546
volumes:
  db-data:
