# This is an example config file for the bot.
# To use this file, copy it and rename it to config.toml.

[break]
break_time = 60
part_break_time = 30

[messages]
no_interaction_message = 'You have to clock in first.'

# Clock In
already_clocked_in_message = 'You are already clocked in.'
cant_reset_time_message = "You can't reset your time once you're already clocked in."
clock_in_message = 'You have clocked in.'
user_clock_in_message = '{user_name} has clocked in.'
not_clocked_in_message = 'You have not clocked in.'
no_permission_clock_message = 'You do not have permission to clock in.'

# Clock Out
clock_out_message = '{user_name} has clocked out.'
clock_out_data_message = '{date} - {user_name} has clocked out.\n**Business Hours**\n{hours} hour{hours_s} and {minutes} minute{minutes_s}\n**Meeting Time**\n{meeting_hours} hour{meeting_hours_s} and {meeting_minutes} minute{meeting_minutes_s}\n**Break Time**\n{break_hours} hour{break_hours_s} and {break_minutes} minute{break_minutes_s}'

# View Time
view_time_message = '**Working time:**\n{business_hours} hour{business_hours_s}, {business_minutes} minute{business_minutes_s} and {business_seconds} second{business_seconds_s}\n**Break time:**\n{break_hours} hour{break_hours_s}, {break_minutes} minute{break_minutes_s} and {break_seconds} second{break_seconds_s}.'

# Break
already_on_break_message = 'You are already on break.'
on_break_message = 'You are now on break.'
user_on_break_message = '{user_name} went on a break.'

# Back
already_back_message = 'You are already back in.'
back_message = 'You are now back in.'
user_back_message = '{user_name} is now back in.'
user_break_back_message = '{user_name} is now back in from a break of {break_hours}h {break_minutes}m.'
user_meeting_back_message = '{user_name} is now back in from a meeting of {meeting_hours}h {meeting_minutes}m.'

# Meeting
user_meeting_message = '{user_name} went to a meeting.'
meeting_message = 'You are now in a meeting.'
already_in_meeting_message = 'You are already in a meeting.'

# Setup
no_permission_setup_message = 'You do not have permission to set up the bot.'